plugins:
  softwareupdate:
    checks:
      octoprint:
        checkout_folder: /OctoPrint
        prerelease: false
        prerelease_channel: null
        type: github_release
webcam:
  ffmpeg: /usr/bin/ffmpeg
  stream: /webcam/?action=stream
  snapshot: /webcam/?action=snapshot
