plugins:
  softwareupdate:
    checks:
      octoprint:
        checkout_folder: /OctoPrint
        prerelease: false
        prerelease_channel: null
        type: github_release
webcam:
  ffmpeg: /usr/local/bin/ffmpeg
